version: '3.8'
services:
  
  deno-prod:
    build:
      context: .
      dockerfile: Dockerfile.deno
    ports:
      - "3009:8000"
    env_file:
      - ./.env
    environment:
      - PORT=8000
    networks:
      - app-network
    command: deno run --allow-net --allow-env --allow-read --allow-write index.ts

networks:
  app-network:
    driver: bridge
