version: '3.8'
services:
  
  deno-prod:
    build:
      context: .
      dockerfile: Dockerfile.deno
    image: javimosch/deno-llm-api-deno:latest #Replace with your Docker Hub username/repository
    ports:
      - "3009:8000"
    env_file:
      - ./.env
    environment:
      - PORT=8000
    command: deno run --allow-net --allow-env --allow-read --allow-write index.ts
