version: '3.8'
services:
  
  deno-prod:
    image: javimosch/deno-llm-api-deno:latest #Replace with your Docker Hub username/repository
    expose:
      - "8000"
    environment:
      - PORT=8000
    networks:
      - app-network
    command: deno run --allow-net --allow-env --allow-read --allow-write index.ts

networks:
  app-network:
    driver: bridge
